use db;

CREATE TABLE my_table(
  id INT(11) PRIMARY KEY AUTO_INCREMENT NOT NULL,
  view VARCHAR(50),
  name VARCHAR(50) NOT NULL,
  hashtag VARCHAR(50) NOT NULL,
  created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP
);
